//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u22749472_HW02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoption
    {
        public int AdoptionID { get; set; }
        public Nullable<int> PetID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual User User { get; set; }
    }
}
